import type { Product } from "@/types";

export const MOCK_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Samsung Galaxy S24 256GB",
    slug: "samsung-galaxy-s24-256gb",
    category: "smartphone",
    brand: "Samsung",
    imageUrl: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=400&h=400&fit=crop",
    description: "Smartphone flagship Samsung dengan chip Exynos 2400, layar 6.2 inch Dynamic AMOLED 2X, dan kamera 50MP.",
    featured: true,
    tags: ["samsung", "flagship", "android", "5g"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    prices: [
      {
        marketplace: "tokopedia",
        price: 10999000,
        originalPrice: 12999000,
        discount: 15,
        affiliateUrl: "https://tokopedia.com/samsung-official",
        productUrl: "https://tokopedia.com/samsung-official/galaxy-s24",
        inStock: true,
        rating: 4.9,
        sold: 1250,
        lastUpdated: new Date().toISOString(),
      },
      {
        marketplace: "shopee",
        price: 10799000,
        originalPrice: 12999000,
        discount: 17,
        affiliateUrl: "https://shopee.co.id/samsung-official",
        productUrl: "https://shopee.co.id/samsung-official/galaxy-s24",
        inStock: true,
        rating: 4.8,
        sold: 980,
        lastUpdated: new Date().toISOString(),
      },
      {
        marketplace: "tiktok",
        price: 11299000,
        originalPrice: 12999000,
        discount: 13,
        affiliateUrl: "https://tiktok.com/@samsung-official",
        productUrl: "https://shop.tiktok.com/samsung/galaxy-s24",
        inStock: true,
        rating: 4.7,
        sold: 430,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: "2",
    name: "Apple AirPods Pro 2nd Gen",
    slug: "apple-airpods-pro-2nd-gen",
    category: "elektronik",
    brand: "Apple",
    imageUrl: "https://images.unsplash.com/photo-1600294037681-c80b4cb5b434?w=400&h=400&fit=crop",
    description: "TWS premium dengan Active Noise Cancellation, chip H2, dan ketahanan baterai hingga 30 jam.",
    featured: true,
    tags: ["apple", "tws", "earphone", "anc"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    prices: [
      {
        marketplace: "tokopedia",
        price: 3499000,
        originalPrice: 3999000,
        discount: 13,
        affiliateUrl: "https://tokopedia.com/ibox-official",
        productUrl: "https://tokopedia.com/ibox-official/airpods-pro-2",
        inStock: true,
        rating: 4.9,
        sold: 2100,
        lastUpdated: new Date().toISOString(),
      },
      {
        marketplace: "shopee",
        price: 3399000,
        originalPrice: 3999000,
        discount: 15,
        affiliateUrl: "https://shopee.co.id/ibox-official",
        productUrl: "https://shopee.co.id/ibox-official/airpods-pro-2",
        inStock: true,
        rating: 4.9,
        sold: 3400,
        lastUpdated: new Date().toISOString(),
      },
      {
        marketplace: "tiktok",
        price: 3599000,
        originalPrice: 3999000,
        discount: 10,
        affiliateUrl: "https://tiktok.com/@ibox-official",
        productUrl: "https://shop.tiktok.com/ibox/airpods-pro-2",
        inStock: false,
        rating: 4.8,
        sold: 210,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: "3",
    name: "Xiaomi Redmi Note 13 Pro 256GB",
    slug: "xiaomi-redmi-note-13-pro-256gb",
    category: "smartphone",
    brand: "Xiaomi",
    imageUrl: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?w=400&h=400&fit=crop",
    description: "Mid-range terbaik dengan kamera 200MP, layar AMOLED 120Hz, dan baterai 5100mAh.",
    featured: true,
    tags: ["xiaomi", "redmi", "android", "midranger"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    prices: [
      {
        marketplace: "tokopedia",
        price: 3199000,
        originalPrice: 3499000,
        discount: 9,
        affiliateUrl: "https://tokopedia.com/xiaomi-official",
        productUrl: "https://tokopedia.com/xiaomi-official/redmi-note-13-pro",
        inStock: true,
        rating: 4.8,
        sold: 5600,
        lastUpdated: new Date().toISOString(),
      },
      {
        marketplace: "shopee",
        price: 3099000,
        originalPrice: 3499000,
        discount: 11,
        affiliateUrl: "https://shopee.co.id/xiaomi-official",
        productUrl: "https://shopee.co.id/xiaomi-official/redmi-note-13-pro",
        inStock: true,
        rating: 4.8,
        sold: 8200,
        lastUpdated: new Date().toISOString(),
      },
      {
        marketplace: "tiktok",
        price: 3249000,
        originalPrice: 3499000,
        discount: 7,
        affiliateUrl: "https://tiktok.com/@xiaomi-official",
        productUrl: "https://shop.tiktok.com/xiaomi/redmi-note-13-pro",
        inStock: true,
        rating: 4.7,
        sold: 1800,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
  {
    id: "4",
    name: "Wardah Lightening Serum 20ml",
    slug: "wardah-lightening-serum-20ml",
    category: "kecantikan",
    brand: "Wardah",
    imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=400&h=400&fit=crop",
    description: "Serum pencerah wajah dengan kandungan Niacinamide dan Vitamin C. Cocok untuk kulit kusam.",
    featured: false,
    tags: ["wardah", "skincare", "serum", "lokal"],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    prices: [
      {
        marketplace: "tokopedia",
        price: 89000,
        originalPrice: 109000,
        discount: 18,
        affiliateUrl: "https://tokopedia.com/wardah-official",
        productUrl: "https://tokopedia.com/wardah-official/lightening-serum",
        inStock: true,
        rating: 4.7,
        sold: 15000,
        lastUpdated: new Date().toISOString(),
      },
      {
        marketplace: "shopee",
        price: 79000,
        originalPrice: 109000,
        discount: 27,
        affiliateUrl: "https://shopee.co.id/wardah-official",
        productUrl: "https://shopee.co.id/wardah-official/lightening-serum",
        inStock: true,
        rating: 4.8,
        sold: 32000,
        lastUpdated: new Date().toISOString(),
      },
      {
        marketplace: "tiktok",
        price: 85000,
        originalPrice: 109000,
        discount: 22,
        affiliateUrl: "https://tiktok.com/@wardah-official",
        productUrl: "https://shop.tiktok.com/wardah/lightening-serum",
        inStock: true,
        rating: 4.9,
        sold: 22000,
        lastUpdated: new Date().toISOString(),
      },
    ],
  },
];
